/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobayer.forms;

import jobayer.info.UserInfo;

/**
 *
 * @author jobayer
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home(String title,String post,String id,String password) {
        initComponents();
        this.setVisible(true);
        this.setTitle(title+" Panel");
        this.showDetails(title, post, id);
        UserInfo.accessLevel=title;
        UserInfo.userId=id;
        UserInfo.post=post;
        UserInfo.password=password;
        this.menuItemPermission();
        
    }
    private void showDetails(String title,String post,String id){
    
    showLevel.setText(title);
    showPost.setText(post);
    showUserId.setText(id);
    
    }
    
    private void menuItemPermission(){
       if(UserInfo.accessLevel.equals("General")){
           addEmployeeMenuItem.setEnabled(false);
           deleteEmployeeMenuItem.setEnabled(false);
           giveAddendanceMenuItem.setEnabled(false);
       
       }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showUserId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showPost = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        showLevel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addEmployeeMenuItem = new javax.swing.JMenuItem();
        updateEmployeeMenuItem = new javax.swing.JMenuItem();
        deleteEmployeeMenuItem = new javax.swing.JMenuItem();
        giveAddendanceMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log in Details");

        jLabel2.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel2.setText("User Id:");

        showUserId.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        showUserId.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel4.setText("Post :");

        showPost.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        showPost.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel6.setText("User Level :");

        showLevel.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        showLevel.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showUserId, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(showPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(showUserId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(showPost))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showLevel)
                    .addComponent(jLabel6))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N

        jMenu1.setBorder(null);
        jMenu1.setText("Manage Employee");
        jMenu1.setAlignmentX(2.0F);

        addEmployeeMenuItem.setText("Add Employee");
        addEmployeeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addEmployeeMenuItem);

        updateEmployeeMenuItem.setText("Update Info");
        updateEmployeeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(updateEmployeeMenuItem);

        deleteEmployeeMenuItem.setText("Delete Employee");
        deleteEmployeeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(deleteEmployeeMenuItem);

        giveAddendanceMenuItem.setText("Give Addendance");
        giveAddendanceMenuItem.setActionCommand("Give Attendence");
        giveAddendanceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveAddendanceMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(giveAddendanceMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
       this.dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void addEmployeeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeMenuItemActionPerformed
         if( AddEmployee.addEmployeeFrame!=null){
                AddEmployee.addEmployeeFrame.dispose();
                AddEmployee.addEmployeeFrame=new AddEmployee();
       }else{
           AddEmployee.addEmployeeFrame=new AddEmployee();
       }
        
    }//GEN-LAST:event_addEmployeeMenuItemActionPerformed

    private void updateEmployeeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeMenuItemActionPerformed
       if(Update.updateFrame!=null){
            Update.updateFrame.dispose();
            Update.updateFrame=new Update();
       }else{
           Update.updateFrame=new Update();
       }
    }//GEN-LAST:event_updateEmployeeMenuItemActionPerformed

    private void deleteEmployeeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeMenuItemActionPerformed
       new DeleteForm();
    }//GEN-LAST:event_deleteEmployeeMenuItemActionPerformed

    private void giveAddendanceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveAddendanceMenuItemActionPerformed
        new AttendanceForm();
    }//GEN-LAST:event_giveAddendanceMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addEmployeeMenuItem;
    private javax.swing.JMenuItem deleteEmployeeMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem giveAddendanceMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel showLevel;
    private javax.swing.JLabel showPost;
    private javax.swing.JLabel showUserId;
    private javax.swing.JMenuItem updateEmployeeMenuItem;
    // End of variables declaration//GEN-END:variables
}
